### ISSUE TITLE
Skills dev giving 404 not found

### ISSUE THREAD

**Issue by mccrodp** [karolsojko/skills-api#7]
I ran through the installation process and all seemed to go smoothly, however I get the following on visiting http://skills.dev/

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<error code="404" message="Not Found"/>
```

The documentation works @ http://skills.dev/api/doc but that's all I can see working at the moment on my setup.

**Comment by karolsojko** [comment]
@mccrodp the endpoints are:

[GET] http://skills.dev/api/v1/skills
[POST] http://skills.dev/api/v1/skills
[DELETE] http://skills.dev/api/v1/skills/:id

so you can try those with curl for example

**Comment by mccrodp** [comment]
Ahh, there's no index (as it's not a website 👍 ), ok great, thanks, will give it a go.
